### ISSUE TITLE
Doesn't seem to work with commands defined as an array

### ISSUE THREAD

**Issue by YarekTyshchenko** [toolmantim/bksr#19]
BK supports command syntax like this:
```yaml
steps:
  - commands:
    - one;
    - two;
    - three;
```

But running `bksr` tool, it tries to run it as a single comma separated command:
```bash
one;,two;,three;
```
