### ISSUE TITLE
`block` steps show up as `[object Object]` in menu

### ISSUE THREAD

**Issue by amasses** [toolmantim/bksr#5]
When running bksr on a pipeline with `block` steps the following is rendered:

![bksr node 2018-05-14 08-46-49](https://user-images.githubusercontent.com/100632/39972452-8d672db2-5753-11e8-8ddd-e6457c882a8f.png)

Excerpt of pipeline: 

```yaml
  - block: ":ship: Release [Sandbox]"
    prompt: "Release to sandbox?"
    branches: "master"
    fields:
      - select: "Release"
        key: "release-to-sandbox"
        default: "no"
        options:
        - label: "Yes"
          value: "yes"
        - label: "No"
          value: "no"

  - command: "bin/release_to_sandbox.sh"
    label: ":capistrano: Deploy [Sandbox]"
    branches: "master"
    agents:
      - "environment=sandbox"
      - "queue=deploy"

  - "wait"
```
